# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: A Smattering of Stories
email: cgathercole@gmail.com
description: >
  initially an experiment to port stories.upthebuzzard.com
  from wordpress.com to Jekyll on GitHub
baseurl: "" # the subpath of your site, e.g. /blog
url: http://upthebuzzard.github.io # stories.upthebuzzard.com # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: upthebuzzard
github_username:  upthebuzzard
githib_repo: https://github.com/upthebuzzard/upthebuzzard.github.io
author: Chris Gathercole
lang: en
default_collection_background_image_url: /assets/P1070749-H800.JPG

google_analytics: UA-92309370-1

license_name: Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License
license_url: http://creativecommons.org/licenses/by-nc-sa/3.0/

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  moose_and_goose_stories:
    output: true
    title: The Moose and Goose Stories
    title_singular: A Moose and Goose Story
    description: a collection of stories about Moose and Goose, Solvers of Tricky Problems
    sequence: 1
    background_image_url: /assets/P1070818-H800.JPG
  grey_parrot_stories:
    output: true
    title: The Grey Parrot Stories
    title_singular: A Grey Parrot Story
    description: a collection of stories about the (too) clever grey parrot
    sequence: 2
    background_image_url: /assets/P1070812-H800.JPG
  predicting_the_present:
    output: true
    title: Predicting the Present
    title_singular: A Predicting the Present Story
    description: this short stories are less predicting the future and more “predicting the present”.
    sequence: 10
  emus_all_the_way_down:
    output: true
    title: Emus All The Way Down
    title_singular: Emus All The Way Down
    description: riffing on the Predicting The Present story "Emus All The Way Down".
    sequence: 11
  fragments:
    output: true
    title: Fragments of writing
    title_singular: A Fragment
    description: riffing on whatever is riff-worthy
    sequence: 20
  distractions:
    output: true
    title: Distractions
    title_singular: A Distraction
    description: a collection of interesting links
    sequence: 90
  jekyll_notes:
    output: true
    title: Jekyll Notes
    title_singular: A Jekyll Note
    description: a collection of notes and observations from and aide-memoires for using Jekyll for the first time.
    sequence: 100
    background_image_url: /assets/JekyllAndHydeWikipedia.jpg
